name: mlops-student-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - jupyter
  - ipykernel
  - pytest
  - pytest-cov
  - pip
  - pip:
    - pytest-cov # Test coverage reporting for code quality and completeness
    - black # Code formatting to enforce style and readability
    - flake8 # Linting to check code for errors and best practices