name: mlops-student-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - jupyter
  - ipykernel
  - pytest
  - pytest-cov
  - pyyaml
  - python-dotenv
  - requests
  - pip
  - pip:
    - pytest-cov
    - black
    - flake8
    - pandera
    - wandb
    - fastapi
    - "uvicorn[standard]"
    - pydantic
    - httpx
    - streamlit
